module.exports = {
	CHANNEL_TYPES: {
		GUILD_TEXT: 0,
		DM: 1,
		GUILD_VOICE: 2,
		GUILD_CATEGORY: 4,
		GUILD_ANNOUNCEMENT: 5,
		ANNOUNCEMENT_THREAD: 10,
		PUBLIC_THREAD: 11,
		PRIVATE_THREAD: 12,
		GUILD_STAGE_VOICE: 13,
		GUILD_DIRECTORY: 14,
		GUILD_FORUM: 15,
	},
	BUTTON_STYLE_TYPES: {
		PRIMARY: 1,
		SECONDARY: 2,
		SUCCESS: 3,
		DANGER: 4,
		LINK: 5,
	},
	SELECT_MENU_TYPES: {
		TEXT: 3,
		USER: 5,
		ROLE: 6,
		MENTIONABLE: 7,
		CHANNELS: 8,
	},
	TEXT_INPUT_STYLES: {
		SHORT: 1,
		LONG: 2,
	},
	NUMBER_INPUT_STYLES: {
		TEN: 1,
		HUNDRED: 2,
		THOUSAND: 3,
	},
};
